reactor:
  step: 1  # state update period in seconds
  work: 86400  # reactor working time in steps
  chance_rate: 0.05  # boom chance rate per step (for abnormal reactor states 100+)
run:
  dump_path: app/reactor.db  # path to db
  plot: yes  # plot reactor state
  simulate: no  # simulate teams actions
  simulate_teams: null # which teams to simulate (null - simulate all, [] - no one)
  simulate_strats: ['staff_1', 'terrors_1', 'govs_1']  # teams strategies
  reset: yes  # reset db before or start from the last saved state
  last_dump: no  # dump only last step (for testing, don't use it during the game)