actions:
- access: [admin]
  cost: 0
  name: boom
  name_ru: взрыв
- access: [admin]
  cost: 0
  name: iodine
  name_ru: иодная яма
- access: [admin]
  cost: 0
  name: reset
  name_ru: сброс
- access: [staff]
  cost: 10
  name: rod_up
  name_ru: поднять стрежни (+5 к мощности, быстро)
- access: [staff]
  cost: 10
  name: rod_down
  name_ru: опустить стрежни (-5 к мощности, быстро)
- access: [staff]
  cost: 5
  name: pump_up
  name_ru: увеличить расход рабочего тела (-5 к мощности, медленно)
- access: [staff]
  cost: 5
  name: pump_down
  name_ru: уменьшить расход рабочего тела (+5 к мощности, медленно)
- access: [staff]
  cost: 25
  name: boron
  name_ru: добавить бора в активную зону (-5 к мощности, очень быстро)
- access: [staff]
  cost: 100
  name: scram
  name_ru: АЗ-5
- access: [staff]
  cost: 150
  name: plant_inspection
  name_ru: Провести инспекцию на станции (50% что их действия не сработают)
- access: [staff]
  cost: 150
  name: bribe_govs
  name_ru: Подкупить чиновников (50% что их действия не сработают)
#- access: [terrors]
#  cost: 1
#  name: replace_boron
- access: [terrors]
  cost: 250
  name: pump_blow_up
  name_ru: взорвать насос (+25 к мощности, быстро)
- access: [terrors]
  cost: 50
  name: pump_break
  name_ru: сломать насос (+25 к мощности, медленно)
- access: [terrors]
  cost: 300
  name: fire
  name_ru: устроить пожар (мощность блока падает до 0)
- access: [terrors]
  cost: 150
  name: virus
  name_ru: запустить вирус (мощность начинает случайно прыгать)
- access: [terrors]
  cost: 150
  name: poison_staff
  name_ru: травануть операторов (50% что их действия не сработают)
- access: [terrors]
  cost: 150
  name: insert_spy
  name_ru: внедрить шпиона в правительство (50% что их действия не сработают)
- access: [govs]
  cost: 25
  name: tip
  name_ru: съэкономить на стержнях (+5 к мощности, очень медленно)
- access: [govs]
  cost: 150
  name: anti_terrorist_operation
  name_ru: антитеррористическая операция (50% что их действия не сработают)
- access: [govs]
  cost: 150
  name: intimidate_staff
  name_ru: запугать персонал (50% что их действия не сработают)
- access: [govs]
  cost: 10
  name: bribe_chief_engineer_plus
  name_ru: подкупить главного инженера (+20 к мощности, медленно)
- access: [terrors]
  cost: 10
  name: bribe_chief_engineer_minus
  name_ru: подкупить главного инженера (-20 к мощности, медленно)
- access: [govs]
  cost: 10
  name: press_operators
  name_ru: заставить станцию выдавать нагрузку (+5 к мощности, быстро)
- access: [govs]
  cost: 75
  name: hide_boom
  name_ru: скрыть аварию (-1 к счетчику аварий, повлияет на победные очки диверсантов)
auth:
  admin: e9c0bd34720a2861ba66d14131963422740238ac031b2ae92fc4f61d2d481d45516a17769504a81873c64c41092ce13f4849aea9de1d6e8f935973070e8ceb8f
  govs: 564b151637e9e9c63a84549bc6f673346cf6e8cae7527a2fe7049ad9898c61d5c8a2a3f91526a6f7433943706d60d15be8f11503ad958935a56e586fffea6a4e
  staff: 1c0551c57543b0580e5641cb5ada812577f335c59155978b090e405950b1a8f36964812ca27651733d32ba35d16fbb78d8e25d365de254ab6363b30af99a6644
  terrors: 49acf48595297df5fe5a31a5865c0d4f31c5c18e1c388b5df3bb5cee7f14195402c478e0157fdef3de1d2be9fbe8302a79e7c5135dc4507e32853a28d981225b
init_ap: 0
promo:
  hesouam: 1000
promos:
  govs:
  - ap: 300
    name: старт
  - ap: 300
    name: 83214
  - ap: 300
    name: ипркн
  - ap: 300
    name: 37938
  - ap: 300
    name: 30111975
  - ap: 300
    name: 20111103
  - ap: 300
    name: 03281979
  - ap: 300
    name: щербина
  - ap: 300
    name: 26041986
  - ap: 300
    name: 19570929
  - ap: 300
    name: хабиб
  - ap: 300
    name: хабибулин
  - ap: 300
    name: никулин
  - ap: 300
    name: бибаибоба
  - ap: 300
    name: жигадрыга
  - ap: 300
    name: косяк
  - ap: 600
    name: косяк2
  - ap: 900
    name: косяк3
  - ap: 1200
    name: косяк4
  - ap: 5000
    name: косяк5
  staff:
  - ap: 300
    name: старт
  - ap: 300
    name: 83214
  - ap: 300
    name: иазсу
  - ap: 300
    name: 103520
  - ap: 300
    name: 30111975
  - ap: 300
    name: 20111103
  - ap: 300
    name: 03281979
  - ap: 300
    name: дятлов
  - ap: 300
    name: 26041986
  - ap: 300
    name: 19570929
  - ap: 300
    name: хабиб
  - ap: 300
    name: хабибулин
  - ap: 300
    name: никулин
  - ap: 300
    name: бибаибоба
  - ap: 300
    name: жигадрыга
  - ap: 300
    name: косяк
  - ap: 600
    name: косяк2
  - ap: 900
    name: косяк3
  - ap: 1200
    name: косяк4
  - ap: 5000
    name: косяк5
  terrors:
  - ap: 300
    name: старт
  - ap: 300
    name: 83214
  - ap: 300
    name: итруч
  - ap: 300
    name: 103872
  - ap: 300
    name: 30111975
  - ap: 300
    name: 20111103
  - ap: 300
    name: 03281979
  - ap: 300
    name: путин
  - ap: 300
    name: 26041986
  - ap: 300
    name: 19570929
  - ap: 300
    name: хабиб
  - ap: 300
    name: хабибулин
  - ap: 300
    name: никулин
  - ap: 300
    name: бибаибоба
  - ap: 300
    name: жигадрыга
  - ap: 300
    name: косяк
  - ap: 600
    name: косяк2
  - ap: 900
    name: косяк3
  - ap: 1200
    name: косяк4
  - ap: 5000
    name: косяк5
  admin:
  - ap: 100500
    name: admin

secret: ahalaymahalay

teams:
- govs
- terrors
- staff
- admin

pair_dashboard_with_controls: True
stats_update_timeout: 1000 # milliseconds, default is 1000 milliseconds
points_amount: 25

plots_access:
  govs:
    time_series:
      - state
    scalars:
      - cur_step
      - cur_timestamp
      - state
      - rate
      - chance
      - booms_cnt
      - staff_cnt
      - govs_cnt
      - terrors_cnt
      - no_one_cnt
  terrors:
    time_series:
      - state
    scalars:
      - cur_step
      - cur_timestamp
      - state
      - rate
      - chance
      - booms_cnt
      - staff_cnt
      - govs_cnt
      - terrors_cnt
      - no_one_cnt

  staff:
    time_series:
      - state
    scalars:
      - cur_step
      - cur_timestamp
      - state
      - rate
      - chance
      - booms_cnt
      - staff_cnt
      - govs_cnt
      - terrors_cnt
      - no_one_cnt
  admin:
    time_series:
      - state
      - rate
      - cur_step
    scalars:
      - cur_step
      - cur_timestamp
      - state
      - rate
      - chance
      - booms_cnt
      - staff_cnt
      - terrors_cnt
      - no_one_cnt
