actions:
- access: [staff]
  cost: 1
  name: rod_up
  work: 1
- access: [staff]
  cost: 1
  name: rod_down
  work: 1
- access: [staff]
  cost: 1
  name: pump_up
  work: 1
- access: [staff]
  cost: 1
  name: pump_down
  work: 1
- access: [staff]
  cost: 1
  name: boron
  work: 1
- access: [staff]
  cost: 1
  name: scram
  work: 1
- access: [terrors]
  cost: 1
  name: deenergizer
  work: 1
- access: [terrors]
  cost: 1
  name: replace_boron
  work: 1
- access: [terrors]
  cost: 1
  name: pump_blow_up
  work: 1
- access: [terrors]
  cost: 1
  name: pump_break
  work: 1
- access: [terrors]
  cost: 1
  name: fire
  work: 1
- access: [govs]
  cost: 1
  name: tip
  work: 1
#- access: [govs]
#  cost: 1
#  name: anti_terrorist_operation
#  work: 1
- access: [govs]
  cost: 1
  name: bribe_chief_engineer
  work: 1
- access: [govs]
  cost: 1
  name: press_operators
  work: 1
#- access: null
#  cost: 0
#  name: steam
#  work: 1
#- access: null
#  cost: 0
#  name: water
#  work: 1
#- access: null
#  cost: 0
#  name: iodine
#  work: 1
#- access: null
#  cost: 0
#  name: boom
#  work: 1
#- access: null
#  cost: 1
#  name: test
#  work: 1
auth:
  admin: e9c0bd34720a2861ba66d14131963422740238ac031b2ae92fc4f61d2d481d45516a17769504a81873c64c41092ce13f4849aea9de1d6e8f935973070e8ceb8f
  govs: 564b151637e9e9c63a84549bc6f673346cf6e8cae7527a2fe7049ad9898c61d5c8a2a3f91526a6f7433943706d60d15be8f11503ad958935a56e586fffea6a4e
  staff: 1c0551c57543b0580e5641cb5ada812577f335c59155978b090e405950b1a8f36964812ca27651733d32ba35d16fbb78d8e25d365de254ab6363b30af99a6644
  terrors: 49acf48595297df5fe5a31a5865c0d4f31c5c18e1c388b5df3bb5cee7f14195402c478e0157fdef3de1d2be9fbe8302a79e7c5135dc4507e32853a28d981225b
init_ap: 0
promo:
  hesouam: 1000
promos:
  govs:
  - ap: 1000
    name: beer
  - ap: 1000
    name: bee
  staff:
  - ap: 100
    name: hesouam
  - ap: 1000
    name: love
  terrors:
  - ap: 1000
    name: ibrae
  - ap: 1000
    name: mipt
secret: ahalaymahalay
teams:
- govs
- terrors
- staff
